### ISSUE TITLE
extra steps

### ISSUE THREAD

**Issue by tardypad** [johndoejdg/mariadb-10.2-archlinux#1]
Thanks a lot for this PKGBUILD
It seems to work fine to me so far

Just in case that might be useful for someone else, here are some extra things I needed:
- move the patch to the `src` folder manually when the build complains about it
- add the following lines at the end of the `package_mariadb` function to prevent some conflicts
```
rm usr/bin/mariadb_config
rm usr/lib/libmariadb*
rm usr/lib/mysql/plugin/auth_gssapi_client.so
rm usr/lib/mysql/plugin/dialog.so
rm usr/lib/mysql/plugin/mysql_clear_password.so
rm usr/lib/mysql/plugin/sha256_password.so
```

**Comment by korvinko** [comment]
@tardypad  thanks for this tips. All changes included in repo.
